trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: bookstore_api
    displayName: "Lint, Test, and Audit NestJS"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "20.x"
        displayName: "Install Node.js"

      - script: |
          npm install -g @nestjs/cli
          npm install
        displayName: "Install dependencies"

      - script: |
          npm run lint
        displayName: "Run lint"

      - script: |
          npm run gitleaks
        displayName: "Run GitLeaks"

      - script: |
          npm run test
        displayName: "Run tests"

      - script: |
          npm audit --audit-level=high
        displayName: "Run npm audit"
        continueOnError: true

      - script: |
          npm run build
        displayName: "Build project"

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "dist"
          ArtifactName: "drop"
          publishLocation: "Container"
        displayName: "Publish build artifacts"