trigger:
  branches:
    include:
      - main  # Trigger the pipeline on changes to the main branch

pool: 
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image provided by Azure Pipelines

jobs:
  - job: bookstore_api
    displayName: "Lint, Test, and Audit NestJS"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "20.x"  # Specify Node.js version
        displayName: "Install Node.js"

      - script: |
          npm install -g @nestjs/cli  # Install NestJS CLI globally
          npm install  # Install project dependencies
        displayName: "Install dependencies"

      - script: |
          npm run lint  # Run linting
        displayName: "Run lint"

      - script: |
          npm run gitleaks  # Run GitLeaks for secret scanning
        displayName: "Run GitLeaks"

      - script: |
          npm run test  # Run tests
        displayName: "Run tests"

      - script: |
          npm audit --audit-level=high  # Run npm audit with high severity level
        displayName: "Run npm audit"
        continueOnError: true  # Continue the pipeline even if audit fails

      - script: |
          npm run build  # Build the project
        displayName: "Build project"

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "dist"  # Path to the build output
          ArtifactName: "drop"  # Name of the artifact
          publishLocation: "Container"  # Publish location
        displayName: "Publish build artifacts"
