version: '3.8'
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=bookstore
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'
  nestjs-app:
    image: booksotre-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5433
      DB_USER: bookstore
      DB_PASSWORD: 123456
      DB_DATABASE: bookstore
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
volumes:
  postgres: